services:
  - type: web
    name: telegram-bot
    env: python
    disk:
      name: sqlite-data
      mountPath: /data
    buildCommand: pip install -r requirements.txt
    startCommand: |
      mkdir -p /data
      python populate_database.py
      python bot.py
    envVars:
      - key: API_TOKEN
        sync: false
      - key: DATA_DIR
        value: /data
    port: 8080
