services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python populate_database.py
      python bot.py
    envVars:
      - key: API_TOKEN
        sync: false
    port: 8080
